# Generated by Django 3.1.2 on 2020-10-27 15:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('active', models.CharField(choices=[('0', 'Inactive'), ('1', 'Active')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tabletwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('other', models.CharField(max_length=200)),
                ('active', models.CharField(choices=[('0', 'Inactive'), ('1', 'Active')], default='1', max_length=1)),
                ('id_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapione.category')),
            ],
        ),
        migrations.CreateModel(
            name='Tableone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('other', models.CharField(max_length=200)),
                ('active', models.CharField(choices=[('0', 'Inactive'), ('1', 'Active')], default='1', max_length=1)),
                ('id_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapione.category')),
            ],
        ),
    ]
